[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
solc = '0.8.7'
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-lib/contracts/=openzeppelin-contracts/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config